// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // db push / migrate 走直连（5432），避免 pgbouncer 连接池不支持 DDL 操作导致卡住
    url: env("DIRECT_URL"),
  },
});
